### ISSUE TITLE
URLs get split up into many small sub-components

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [Vankka/MCDiscordReserializer#1] opened 2020-10-26 19:20 UTC
When serializing an Discord message containing one or multiple URLs the URL part gets split up into many small parts.
Discovered by trying to make URLs in the component clickable.

Example:
Source message: `more test http://anTest.com/ even more test https://google.com/ `
Output as serialized JSON (using GsonComponentSerializer): 
```json
{"text":"","extra":[{"text":"more test "},{"text":"h"},{"text":"t"},{"text":"t"},{"text":"p"},{"text":":"},{"text":"/"},{"text":"/anTest"},{"text":".com even more test "},{"text":"h"},{"text":"t"},{"text":"t"},{"text":"p"},{"text":"s"},{"text":":"},{"text":"/"},{"text":"/google"},{"text":".com"}]}
```

I am using MCDiscordReserializer version 4.0.0 with adventure api 4.0.0.

**Comment by Vankka** [comment] 2020-10-26 19:37
This is something caused by the default text pattern used by the default [Text rule in Discord's SimpleAST](https://github.com/discord/SimpleAST/blob/e0e47e016d65b9804c8657f8b0f1c7f4c37ca869/simpleast-core/src/main/java/com/discord/simpleast/core/simple/SimpleMarkdownRules.kt#L24), absolutely no clue why it uses such a pattern to break at symbols, I'll revise this soon. 

For the time being you can provide a `MinecraftSerializerOptions` with a different set of [rules](https://github.com/Vankka/MCDiscordReserializer/blob/master/src/main/java/dev/vankka/mcdiscordreserializer/minecraft/MinecraftSerializerOptions.java#L59), example;
```java
        // false = no text rule
        List<Rule<Object, Node<Object>, Object>> rules = new ArrayList<>(DiscordMarkdownRules.createAllRulesForDiscord(false));
        rules.add(new Rule<Object, Node<Object>, Object>(Pattern.compile("(.*)")) {
            @Override
            public ParseSpec<Object, Node<Object>, Object> parse(Matcher matcher, Parser<Object, Node<Object>, Object> parser, Object state) {
                return ParseSpec.createTerminal(new TextNode<>(matcher.group()), state);
            }
        });
        MinecraftSerializerOptions options = MinecraftSerializerOptions.defaults().withRules(rules);
        
        // passing the options during serialization
        MinecraftSerializer.INSTANCE.serialize("some message", options);
        
        // or alternatively with a MinecraftSerializer instance with the given options
        new MinecraftSerializer(options).serialize("some message");
```
(haven't tested, but should theoretically work)

**Comment by ErdbeerbaerLP** [comment] 2020-10-26 20:28
Just tested and this works fine ;)
Now I finally have clickable URLs ingame.

(keeping this open, so others see this workaround until it is fixed in SimpleAST)

**Comment by Vankka** [comment] 2020-10-27 20:53
From going through & switching to a text pattern that doesn't split every special character, the code I provided might not exactly work. I've pushed a snapshot `4.1.0-SNAPSHOT` that has a new text rule, on the default MinecraftSerializer

EDIT: Major 4 not 1, the version is `4.1.0-SNAPSHOT`

**Comment by Vankka** [comment] 2021-01-25 14:52
I reverted what I had done previously because it resulted in some things not being parsed properly. `4.1.1-SNAPSHOT` just combines the text nodes together whenever possible. Closing as the issue is now fixed

**Closed as completed by Vankka** 2021-01-25 14:52 UTC
